name = "Rallous Frontier"
author = "Rallous System"
version = "0.1.0"
pack-format = "packwiz:1.1.0"
description = "Prototype Minecraft pack: original grimdark + prehistoric survival (Warhammer-inspired, Ark-like). Default set avoids Games Workshop and Wildcard IP."

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf690ea4e2f2e8c6c68ff396234e0963bba2c826745faef005ae93316e21c938"

[versions]
minecraft = "1.20.1"
forge = "47.4.0"
