package com.rallous.recruitsbridge;

/**
 * Compiled camp display names, same order as rallous_recruits_bind:name/set
 * and compile_factions.py (1 = Blooded-Axe Tribe … 129 = Vampire Counts).
 */
public final class FactionNames {
    private static final String[] NAMES = {
            "Blooded-Axe Tribe",
            "Harbinger of Disaster",
            "Jagged-Horn Tribe",
            "Manblight Tribe",
            "Redhorn Tribe",
            "Ripper-Horn Tribe",
            "Shadowgor Warherd",
            "Skrinderkin Warherd",
            "Slaughterhorn Tribe",
            "Stone-Horn Tribe",
            "Warherd of the One-Eye",
            "Warherd of the Shadowgave",
            "Barak Varr",
            "Clan Angrund",
            "Clan Helhein",
            "Greybeard's Prospectors",
            "Ironbrow's Expedition",
            "Karak Azorn",
            "Karak Azul",
            "Karak Hirn",
            "Karak Kadrin",
            "Karak Norn",
            "Karak Ziflin",
            "Karaz-a-Karak",
            "Masters of Innovation",
            "Spine of Sotek Dwarfs",
            "The Ancestral Throng",
            "Zhufbar",
            "Averland",
            "Cult of Sigmar",
            "Hochland",
            "Marienburg",
            "Middenland",
            "Nordland",
            "Ostermark",
            "Ostland",
            "Reikland",
            "Stirland",
            "Talabecland",
            "The Golden Order",
            "The Huntsmarshal's Expedition",
            "Wissenland & Nuln",
            "Arachnos",
            "Black Venom",
            "Bloody Spearz",
            "Blue Vipers",
            "Bonerattlaz",
            "Broken Axe",
            "Broken Chainz",
            "Broken Nose",
            "Cluster-Eye Tribe",
            "Creeping Death",
            "Crooked Moon Mutinous Gits",
            "Crooked Moon",
            "Da Cage Breakaz",
            "Dark Land Orcs",
            "Dimmed Sunz",
            "Drippin Fangs",
            "Grimgor's 'Ardboyz",
            "Ironclaw Orcs",
            "Leaf-Cutterz Tribe",
            "Moon Howlerz",
            "Red Cloud",
            "Red Eye",
            "Red Fangs",
            "Scabby Eye",
            "Skull Crag",
            "Skull-takerz",
            "Skullsmasherz",
            "Slaves of Zharr",
            "Teef Snatchaz",
            "The Black Pit Tribe",
            "The Bloody Handz",
            "Top Knotz",
            "Tusked Sunz",
            "Blooded Wanderers",
            "Bloody Sword",
            "Brazen Throne",
            "Challengers of Khorne",
            "Crimson Skull",
            "Exiles of Khorne",
            "Kharneth's Sons",
            "Cult of Sotek",
            "Ghosts of Pahuax",
            "Hexoatl",
            "Itza",
            "Last Defenders",
            "Sentinels of Xeti",
            "Southern Sentinels",
            "Spirit of the Jungle",
            "Tepok's Spawn",
            "Tlaqua",
            "Tlaxtlan",
            "Wardens of the Living Pools",
            "Xlanhuapec",
            "Zlatlan",
            "Clan Carrion",
            "Clan Eshin",
            "Clan Gnaw",
            "Clan Gritus",
            "Clan Kreepus",
            "Clan Krizzor",
            "Clan Mange",
            "Clan Morbidus",
            "Clan Mordkin",
            "Clan Mors",
            "Clan Moulder",
            "Clan Pestilens",
            "Clan Rictus",
            "Clan Septik",
            "Clan Skrat",
            "Clan Skryre",
            "Clan Spittel",
            "Clan Treecherik",
            "Clan Verms",
            "Caravan of Blue Roses",
            "Jiangshi Rebels",
            "Lahmian Sisterhood",
            "Mousillon",
            "Necrarch Brotherhood",
            "Sires of Mourkain",
            "Strygos Empire",
            "Sylvania",
            "Templehof",
            "The Barrow Legion",
            "The Court of Night",
            "The Drakenhof Conclave",
            "The Silver Host",
            "Vampire Counts"
    };

    private FactionNames() {}

    public static String name(int id) {
        if (id < 1 || id > NAMES.length) {
            return null;
        }
        return NAMES[id - 1];
    }
}
